### ISSUE TITLE
Contributers image in readme

### ISSUE THREAD

**Issue by Ankurrawat-12** [Hariom8799/MySathi#5]

**Comment by Ankurrawat-12** [comment]
Hi @Hariom8799 I would love to fix this issue please can you assign me this, and also add the hacktoberfest , hacktoberfest-accepted label.

**Comment by Hariom8799** [comment]
@Beast71421 assigned

**Comment by Ankurrawat-12** [comment]
thanks i will do it quickly

**Comment by Ankurrawat-12** [comment]
done, can you check the pr
